<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [ ]:

# Your code here
#ASSERT:
#    assert [condition you want],[message when condition fails]

In [2]:
x=10
assert x >= 0, "x is becoming negative!"

In [3]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [ ]:

# Your code here


In [5]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.hahaha


ValueError: invalid literal for int() with base 10: 'hahaha'

In [6]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.hahaha
Oh oh! I cannot square hahaha!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [ ]:

# Your code here


In [8]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

In [9]:
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

SyntaxError: positional argument follows keyword argument (25483117.py, line 1)

### 2.2 Docstrings

In [ ]:

# Your code here


In [1]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [2]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [3]:

# Your code here
import numpy as np

In [5]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)  # means 0 because number is too small      
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

-1.0

### 2.4 More unpacking

In [ ]:

# Your code here


In [6]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [7]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [10]:
x, *y, z = np.array([1, 2, 3, 4, 5]) #* is used to denote everything in between
print(x, y, z)

1 [2, 3, 4] 5


In [11]:
x, y*, z = np.array([1, 2, 3, 4, 5]) #* is used to denote everything in between
print(x, y, z)

SyntaxError: invalid syntax (995507998.py, line 1)

In [9]:
x, *_, y = [1, 2, 3, 4, 5] #_ is used to void things in between
print(x, y)


1 5


## Exercise 1 :  A better calculator I

In [ ]:



# Your solution here




In [78]:

def add(x,y):
    return x+y 
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    assert not any(y==0), "Undefined!"
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])


print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [ ]:



# Your solution here




In [79]:

def add(x,y):
    return x+y 
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    try:
        assert not any(y==0), 'Error1'
        return x/y
    except Exception as e:
        print(repr(e))
        print('Error2')

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])


print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100  27]
[-28 -32 -12  52  27]
[2304 2244 2464 1824    0]
AssertionError('Error1')
Error2
None
