<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:

# Your code here


In [2]:
import numpy as np

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [4]:
x[0]

'a1'

In [5]:
x[-1]

'j10'

In [10]:
x[1:3]

array(['b2', 'c3'], dtype='<U3')

In [8]:
print(x[1:3])

['b2' 'c3']


In [9]:
print(x[0:3])

['a1' 'b2' 'c3']


In [12]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [14]:
x[5:2]

array([], dtype='<U3')

In [15]:
x[:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [16]:
x[3:]

array(['d4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [17]:
x[::1]

array(['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'],
      dtype='<U3')

In [18]:
x[::2]

array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

In [19]:
x[3::2]

array(['d4', 'f6', 'h8', 'j10'], dtype='<U3')

In [21]:
x[:9:4]

array(['a1', 'e5', 'i9'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [ ]:

# Your code here


In [22]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [23]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
second_mask = np_array<6
np_array<6
print (second_mask)
np_array[second_mask]

[ True  True  True  True  True False False False False False]


array([1, 2, 3, 4, 5])

In [33]:
np_array<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [35]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [36]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [37]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

In [38]:
np_array[(np_array < 3) or (np_array > 8)]         # '|' means 'OR'  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
#must use bitwise notation

### 1.3 Indexing & Slicing 2D Lists

In [ ]:

# Your code here


In [41]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [42]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [43]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [44]:
py_list_2d[3][1]

'D'

In [45]:
py_list_2d[3][2]

IndexError: list index out of range

In [46]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [47]:
py_list_2d[:3][0]

[1, 'A']

In [48]:
py_list_2d[3::2][1]

[6, 'F']

In [49]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [ ]:

# Your code here


In [50]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [51]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [52]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [53]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [54]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [55]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [56]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [57]:
np_array_2d[3:6:2, 0]

array(['4', '6'], dtype='<U21')

In [ ]:
#Lists: uses [] for both index and position, e.g. np_list_2d[start:stop:step][x]
#Array: uses only one [] but uses comma inside to separate index and position,e.g. np_array_2d[start:stop:step , x ]
#where x is the position in the index

In [60]:
np_array_2d_version2 = np.array([[1, "A", 11, 'K'], [2, "B", 12, 'L'], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

/var/folders/hs/sb4mpcn56nd0jfpfgz57hkh40000gn/T/ipykernel_63900/193365604.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_array_2d_version2 = np.array([[1, "A", 11, 'K'], [2, "B", 12, 'L'], [3, "C"], [4, "D"],


In [61]:
np_array_2d_version2 = np.ndarray([[1, "A", 11, 'K'], [2, "B", 12, 'L'], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

TypeError: 'list' object cannot be interpreted as an integer

In [63]:
np_array_2d_version2 = np.ndarray([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

TypeError: 'list' object cannot be interpreted as an integer

In [66]:
np_array_2d_version2 = np.array([[1, "A", 11, 'K'], [2, "B", 12, 'L']])

In [85]:
np_array_2d_version2[::,2:4] #dosen't matter single: or double: if printing whole set, it will be [start:end:1]

array([['11', 'K'],
       ['12', 'L']], dtype='<U21')

In [75]:
np_array_2d_version2[::,2&3]

array(['11', '12'], dtype='<U21')

In [72]:
np_array_2d_version2[::,2]

array(['11', '12'], dtype='<U21')

### 1.5 Growing lists

In [ ]:

# Your code here


In [89]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [79]:
x=np.array([1,2])
x*10

array([10, 20])

In [93]:
test_list = [1, 2, 3]
test_list + 10 #list add to list no list to integer

TypeError: can only concatenate list (not "int") to list

In [90]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [91]:
[2]

[2]

In [81]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [82]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [83]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [109]:
x=[1,2,3]
x+=[2]
x

[1, 2, 3, 2]

In [96]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


In [97]:
a=(1, 2, 3)     # Define tuple

In [98]:
print(a[0])    # Access data

1


In [100]:
a[0]

1

In [101]:
a[1]

2

In [102]:
a[2]

3

In [103]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


In [111]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
x

[1, 2, 3]

In [112]:
y

[1, 2, 3]

In [113]:
z

[1, 2, 3]

In [114]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [115]:
x

[1, 2, 3]

In [116]:
y

[1, 2, 3]

In [117]:
z

[1, 2, 3]

## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




| Term    |  Brief Discription   |
| :--- | ---: |
| Subsetting |  to select or choose the things we want ie. ranage  |
| Indexing |  Choosing an element(could be groups) |
| Slicing | Picking out specific parts(range) we want out of a list/array/tupule(?)  |
| Masking | Picking out specific parts we want(range) out of a array only given conditions eg. >5|

## Exercise 2 :  Show me the ‘odd’ letters

In [ ]:



# Your solution here




In [119]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [122]:
np_array_2d[::,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')