<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:

# Your code here


In [9]:
import numpy as np

In [60]:
#List
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [61]:
#Numpy Array
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [6]:
#Dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [ ]:

# Your code here


In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [8]:
print(py_real_names[0])

Natasha Romanoff


In [9]:
print(py_super_names[0])

Black Widow


In [10]:
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

Doctor Strange


In [11]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [ ]:

# Your code here


In [12]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [13]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [14]:
print(superhero_info['Black Widow'])

KeyError: 'Black Widow'

In [18]:
print(superhero_info["Tony Stark"])

Iron Man


In [17]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [19]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [35]:
print(superhero_info.values("Black Widow"))

TypeError: dict.values() takes no arguments (1 given)

### 1.4 Higher dimensional lists

In [ ]:

# Your code here


In [20]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [24]:
print(py_superhero_info[1])

['Tony Stark', 'Iron Man']


In [25]:
print(py_superhero_info[1][1])

Iron Man


## 2 Lists vs. Arrays

### 2.1 Size

In [ ]:

# Your code here


In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [5]:
len(py_list_2d)

10

In [6]:
len(np_array_2d)

10

In [7]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [ ]:

# Your code here


In [8]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

In [11]:
py_list = [1, 1.5, 2.5]
np.array(py_list)

array([1. , 1.5, 2.5])

In [15]:
py_list = ['D', 'G', 'A' , 'l']
np.array(py_list)

array(['D', 'G', 'A', 'l'], dtype='<U1')

### 2.3 Adding a number

In [ ]:

# Your code here


In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [19]:
py_list + 10        # Won't work!(List)

TypeError: can only concatenate list (not "int") to list

In [18]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [ ]:

# Your code here


In [20]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [21]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [22]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [26]:
py_list_1 - py_list_2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [27]:
np_array_1 - np_array_2

array([ -9, -18, -27, -36, -45])

### 2.5 Multiplying by a Number

In [ ]:

# Your code here


In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [24]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [28]:
py_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [29]:
np_array/2

array([0.5, 1. , 1.5, 2. , 2.5])

### 2.6 Squaring

In [ ]:

# Your code here


In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [32]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [33]:
py_list//2

TypeError: unsupported operand type(s) for //: 'list' and 'int'

In [34]:
py_list%2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [38]:
np_array//2 #floor fn

array([0, 1, 1, 2, 2])

In [39]:
np_array%2 #modulo

array([1, 0, 1, 0, 1])

### 2.7 Asking questions

In [ ]:

# Your code here


In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [43]:
py_list == 3     # Works, but what IS the question? 
                 # Does py_list contain only the element 3 only?

False

In [44]:
py_list > 3      # Won't work!
                 # Not a valid fn since comparing lists and int?

TypeError: '>' not supported between instances of 'list' and 'int'

In [47]:
np_array == 3     #checks through every value inside the array

array([False, False,  True, False, False])

In [46]:
np_array > 3  

array([False, False, False,  True,  True])

In [48]:
(np_array/2)>1

array([False, False,  True,  True,  True])

In [49]:
(np_array//2)>1

array([False, False, False,  True,  True])

In [51]:
(np_array%2)>1

array([False, False, False, False, False])

In [52]:
(np_array%3)>1

array([False,  True, False, False,  True])

### 2.8 Mathematics

In [ ]:

# Your code here


In [53]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [62]:
sum(py_list)     # sum() is a base Python function

15

In [63]:
max(py_list)     # max() is a base Python function

5

In [64]:
min(py_list)     # min() is a base Python function

1

In [65]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [71]:
np.mean(py_list)

3.0

In [74]:
np_array.sum()  #is 74 and 72 the same

15

In [72]:
sum(np_array)

15

In [67]:
np_array.mean()

3.0

In [68]:
np_array.max()

5

In [69]:
np_array.min()

1

## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




Two similarities between lists and arrays.
1. Both lists and arrays store information be it int,str or float
2. The order of variables in lists and arrays matters
*3. Assessing information uses a zero-indexed language*

Two differences between lists and arrays.
1. Lists is not type dependent but 
   arrays are type dependent(float,int,str)-everything in an array must be of a same type
2. When applying functions, lists can perform function only by taking the whole list (all teh variable together) given while arrays is able to apply the function to each variable in the array

## Exercise 2 :  Index me

In [ ]:



# Your solution here




In [75]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'

i9


In [76]:
int(py_list)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [95]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
py_array = np.array(py_list)
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'
print(py_list[0:10:2])

i9
['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [ ]:



# Your solution here




In [102]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

In [113]:
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


In [125]:
for key,value in superhero_info.items():
    print(key,value)

Natasha Romanoff BLACK WIDOW
Tony Stark IRON MAN
Stephen Strange DOCTOR STRANGE


In [124]:
for key,value in superhero_info.items():
    print(f' {key}, {value}')

 Natasha Romanoff, BLACK WIDOW
 Tony Stark, IRON MAN
 Stephen Strange, DOCTOR STRANGE


## Exercise 4 :  How many ones

In [ ]:



# Your solution here




In [5]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

In [10]:
np_array=np.array(numbers)

In [11]:
if any(np_array==1):
    print('1')

1


In [16]:
x=np_array==1


In [17]:
np_array.sum()

2192

In [21]:
(np_array==1).sum()


9

In [24]:
np_array==1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [28]:
x=np_array==1  #x=(np_array==1)

In [29]:
x.sum()

9

In [18]:
np_array

array([45, 60,  1, 30, 96,  1, 96, 57, 16,  1, 99, 62, 86, 43, 42, 60, 59,
        1,  1, 35, 83, 47, 34, 28, 68, 23, 22, 92,  1, 79,  1, 29, 94, 72,
       46, 47,  1, 74, 32, 20,  8, 37, 35,  1, 89, 29, 86, 19, 43, 61])

In [22]:
x.sum()

9